// @generated by lenso-contract-codegen; do not edit.
use std::{fmt, rc::Rc};
use futures::future::LocalBoxFuture;
use lenso_kernel::{InvocationContext, NativeRequestEndpoint, NativeRequestFuture, NativeRequestHandle, PluginDependencies, RequestCapability, RuntimeFailure};

use lenso_plugin_authoring::{BoundCapabilityClient, CapabilityClient, CapabilityClientMany};
pub const CAPABILITY_ID: &str = "lenso.usage-meter@1";
pub const DESCRIPTOR_VERSION: &str = "1.0.0";
pub const PORTABLE: bool = true;
pub const CROSS_LANE_TRANSFER: bool = true;
pub const USAGE_METER_CAPABILITY_ID: &str = CAPABILITY_ID;
pub const USAGE_METER_DESCRIPTOR_VERSION: &str = DESCRIPTOR_VERSION;

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_provided_usage_meter { () => { "{\"capability_id\":\"lenso.usage-meter@1\",\"descriptor_version\":\"1.0.0\",\"operations\":[\"correct_usage\",\"read_usage_window\",\"record_usage\"],\"operation_kinds\":{},\"default_admission\":{\"queue_capacity\":0,\"max_concurrency\":1},\"operation_admissions\":{},\"event_admission\":null,\"cross_lane_transfer\":true}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_usage_meter_client { () => { "{\"capability_id\":\"lenso.usage-meter@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"one\"}" }; }

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_required_many_usage_meter_client { () => { "{\"capability_id\":\"lenso.usage-meter@1\",\"descriptor_version\":\"1.0.0\",\"cardinality\":\"many\"}" }; }

pub const CORRECT_USAGE_OPERATION: &str = "correct_usage";
pub const READ_USAGE_WINDOW_OPERATION: &str = "read_usage_window";
pub const RECORD_USAGE_OPERATION: &str = "record_usage";

pub use lenso_contract_runtime::{Timestamp, UnknownDomainError};
use lenso_contract_runtime::{decode_portable_json, encode_portable_json};

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CorrectUsageRequest {
    #[serde(rename = "correction_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub correction_id: String,
    #[serde(rename = "original_event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub original_event_id: String,
    #[serde(rename = "quantity_delta")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub quantity_delta: String,
    #[serde(rename = "reason")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub reason: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CorrectUsageResponse {
    #[serde(rename = "accepted")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted: bool,
    #[serde(rename = "aggregate_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub aggregate_revision: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum CorrectUsageError {
    Forbidden,
    IdempotencyConflict,
    InvalidCorrection,
    OriginalNotFound,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadUsageWindowRequest {
    #[serde(rename = "meter")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub meter: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
    #[serde(rename = "window_end")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub window_end: Timestamp,
    #[serde(rename = "window_start")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub window_start: Timestamp,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct ReadUsageWindowResponse {
    #[serde(rename = "aggregate_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub aggregate_revision: i64,
    #[serde(rename = "event_count")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_count: i64,
    #[serde(rename = "quantity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub quantity: String,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ReadUsageWindowError {
    Forbidden,
    InvalidWindow,
    Unknown(UnknownDomainError),
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RecordUsageRequest {
    #[serde(rename = "event_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub event_id: String,
    #[serde(rename = "meter")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub meter: String,
    #[serde(rename = "occurred_at")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub occurred_at: Timestamp,
    #[serde(rename = "quantity")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub quantity: String,
    #[serde(rename = "scope_id")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_id: String,
    #[serde(rename = "scope_kind")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub scope_kind: String,
    #[serde(rename = "subject")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub subject: String,
}

#[derive(Clone, Debug, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct RecordUsageResponse {
    #[serde(rename = "accepted")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub accepted: bool,
    #[serde(rename = "aggregate_revision")]
    #[serde(deserialize_with = "lenso_contract_runtime::serde::deserialize_required")]
    pub aggregate_revision: i64,
}

#[derive(Clone, Debug, PartialEq)]
pub enum RecordUsageError {
    Forbidden,
    IdempotencyConflict,
    InvalidEvent,
    Unknown(UnknownDomainError),
}

#[derive(Debug)]
pub struct UsageMeterCorrectUsage;
impl RequestCapability for UsageMeterCorrectUsage {
    type Request = CorrectUsageRequest;
    type Response = CorrectUsageResponse;
    type DomainError = CorrectUsageError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != CORRECT_USAGE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<UsageMeterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).correct_usage(context, request)
    }
}

#[derive(Debug)]
pub struct UsageMeterReadUsageWindow;
impl RequestCapability for UsageMeterReadUsageWindow {
    type Request = ReadUsageWindowRequest;
    type Response = ReadUsageWindowResponse;
    type DomainError = ReadUsageWindowError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != READ_USAGE_WINDOW_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<UsageMeterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).read_usage_window(context, request)
    }
}

#[derive(Debug)]
pub struct UsageMeterRecordUsage;
impl RequestCapability for UsageMeterRecordUsage {
    type Request = RecordUsageRequest;
    type Response = RecordUsageResponse;
    type DomainError = RecordUsageError;
    const ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn invoke_native(endpoint: &dyn NativeRequestEndpoint, operation: &str, request: Self::Request, context: InvocationContext) -> NativeRequestFuture<Self> {
        if operation != RECORD_USAGE_OPERATION {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        }
        let Some(typed_endpoint) = endpoint
            .typed_endpoint()
            .and_then(|endpoint| endpoint.downcast_ref::<UsageMeterRequestEndpoint>())
        else {
            return lenso_kernel::invoke_typed_or_erased_native_request::<Self>(endpoint, operation, request, context);
        };
        Rc::clone(&typed_endpoint.provider).record_usage(context, request)
    }
}

impl serde::Serialize for CorrectUsageError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidCorrection => serializer.serialize_str("invalid_correction"),
            Self::OriginalNotFound => serializer.serialize_str("original_not_found"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for CorrectUsageError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_correction" => Ok(Self::InvalidCorrection),
                "original_not_found" => Ok(Self::OriginalNotFound),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for ReadUsageWindowError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::InvalidWindow => serializer.serialize_str("invalid_window"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for ReadUsageWindowError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "invalid_window" => Ok(Self::InvalidWindow),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

impl serde::Serialize for RecordUsageError {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        use serde::ser::SerializeMap;
        match self {
            Self::Forbidden => serializer.serialize_str("forbidden"),
            Self::IdempotencyConflict => serializer.serialize_str("idempotency_conflict"),
            Self::InvalidEvent => serializer.serialize_str("invalid_event"),
            Self::Unknown(value) => {
                let mut map = serializer.serialize_map(Some(1 + usize::from(value.payload.is_some()) + value.extra.len()))?;
                map.serialize_entry("code", &value.code)?;
                if let Some(payload) = &value.payload {
                    map.serialize_entry("payload", payload)?;
                }
                for (key, extra) in &value.extra {
                    map.serialize_entry(key, extra)?;
                }
                map.end()
            },
        }
    }
}

impl<'de> serde::Deserialize<'de> for RecordUsageError {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = <serde_json::Value as serde::Deserialize>::deserialize(deserializer)?;
        match value {
            serde_json::Value::String(code) => match code.as_str() {
                "forbidden" => Ok(Self::Forbidden),
                "idempotency_conflict" => Ok(Self::IdempotencyConflict),
                "invalid_event" => Ok(Self::InvalidEvent),
                _ => Ok(Self::Unknown(UnknownDomainError { code, payload: None, extra: std::collections::BTreeMap::new() })),
            },
            serde_json::Value::Object(mut object) => {
                let Some(code) = object.remove("code").and_then(|value| value.as_str().map(ToOwned::to_owned)) else {
                    return Err(serde::de::Error::custom("Domain Error object is missing a string code"));
                };
                let payload = object.remove("payload");
                let extra = object.into_iter().collect::<std::collections::BTreeMap<_, _>>();
                Ok(Self::Unknown(UnknownDomainError { code, payload, extra }))
            }
            other => Err(serde::de::Error::custom(format!("Domain Error must be a string or object, got {other}"))),
        }
    }
}

pub fn encode_correct_usage_request(value: &CorrectUsageRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_correct_usage_request(wire: &str) -> Result<CorrectUsageRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_correct_usage_response(value: &CorrectUsageResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_correct_usage_response(wire: &str) -> Result<CorrectUsageResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_correct_usage_error(value: &CorrectUsageError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_correct_usage_error(wire: &str) -> Result<CorrectUsageError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_read_usage_window_request(value: &ReadUsageWindowRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_usage_window_request(wire: &str) -> Result<ReadUsageWindowRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_usage_window_response(value: &ReadUsageWindowResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_usage_window_response(wire: &str) -> Result<ReadUsageWindowResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_read_usage_window_error(value: &ReadUsageWindowError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_read_usage_window_error(wire: &str) -> Result<ReadUsageWindowError, serde_json::Error> { decode_portable_json(wire) }

pub fn encode_record_usage_request(value: &RecordUsageRequest) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_record_usage_request(wire: &str) -> Result<RecordUsageRequest, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_record_usage_response(value: &RecordUsageResponse) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_record_usage_response(wire: &str) -> Result<RecordUsageResponse, serde_json::Error> { decode_portable_json(wire) }
pub fn encode_record_usage_error(value: &RecordUsageError) -> Result<String, serde_json::Error> { encode_portable_json(value) }
pub fn decode_record_usage_error(wire: &str) -> Result<RecordUsageError, serde_json::Error> { decode_portable_json(wire) }

#[doc(hidden)]
pub trait __LensoIntoUsageMeterCorrectUsageResult {
    fn __lenso_into_result(self) -> Result<Result<CorrectUsageResponse, CorrectUsageError>, RuntimeFailure>;
}
impl __LensoIntoUsageMeterCorrectUsageResult for Result<CorrectUsageResponse, CorrectUsageError> {
    fn __lenso_into_result(self) -> Result<Result<CorrectUsageResponse, CorrectUsageError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoUsageMeterCorrectUsageResult for Result<Result<CorrectUsageResponse, CorrectUsageError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<CorrectUsageResponse, CorrectUsageError>, RuntimeFailure> { self }
}
impl __LensoIntoUsageMeterCorrectUsageResult for Result<CorrectUsageResponse, lenso_plugin_authoring::PluginError<CorrectUsageError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<CorrectUsageResponse, CorrectUsageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoUsageMeterCorrectUsageResult for Result<CorrectUsageResponse, UsageMeterCorrectUsageInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<CorrectUsageResponse, CorrectUsageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(UsageMeterCorrectUsageInvocationError::Domain(error)) => Ok(Err(error)),
            Err(UsageMeterCorrectUsageInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoUsageMeterReadUsageWindowResult {
    fn __lenso_into_result(self) -> Result<Result<ReadUsageWindowResponse, ReadUsageWindowError>, RuntimeFailure>;
}
impl __LensoIntoUsageMeterReadUsageWindowResult for Result<ReadUsageWindowResponse, ReadUsageWindowError> {
    fn __lenso_into_result(self) -> Result<Result<ReadUsageWindowResponse, ReadUsageWindowError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoUsageMeterReadUsageWindowResult for Result<Result<ReadUsageWindowResponse, ReadUsageWindowError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<ReadUsageWindowResponse, ReadUsageWindowError>, RuntimeFailure> { self }
}
impl __LensoIntoUsageMeterReadUsageWindowResult for Result<ReadUsageWindowResponse, lenso_plugin_authoring::PluginError<ReadUsageWindowError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<ReadUsageWindowResponse, ReadUsageWindowError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoUsageMeterReadUsageWindowResult for Result<ReadUsageWindowResponse, UsageMeterReadUsageWindowInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<ReadUsageWindowResponse, ReadUsageWindowError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(UsageMeterReadUsageWindowInvocationError::Domain(error)) => Ok(Err(error)),
            Err(UsageMeterReadUsageWindowInvocationError::Runtime(error)) => Err(error),
        }
    }
}

#[doc(hidden)]
pub trait __LensoIntoUsageMeterRecordUsageResult {
    fn __lenso_into_result(self) -> Result<Result<RecordUsageResponse, RecordUsageError>, RuntimeFailure>;
}
impl __LensoIntoUsageMeterRecordUsageResult for Result<RecordUsageResponse, RecordUsageError> {
    fn __lenso_into_result(self) -> Result<Result<RecordUsageResponse, RecordUsageError>, RuntimeFailure> { Ok(self) }
}
impl __LensoIntoUsageMeterRecordUsageResult for Result<Result<RecordUsageResponse, RecordUsageError>, RuntimeFailure> {
    fn __lenso_into_result(self) -> Result<Result<RecordUsageResponse, RecordUsageError>, RuntimeFailure> { self }
}
impl __LensoIntoUsageMeterRecordUsageResult for Result<RecordUsageResponse, lenso_plugin_authoring::PluginError<RecordUsageError, RuntimeFailure>> {
    fn __lenso_into_result(self) -> Result<Result<RecordUsageResponse, RecordUsageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(lenso_plugin_authoring::PluginError::Domain(error)) => Ok(Err(error)),
            Err(lenso_plugin_authoring::PluginError::Runtime(error)) => Err(error),
        }
    }
}
impl __LensoIntoUsageMeterRecordUsageResult for Result<RecordUsageResponse, UsageMeterRecordUsageInvocationError> {
    fn __lenso_into_result(self) -> Result<Result<RecordUsageResponse, RecordUsageError>, RuntimeFailure> {
        match self {
            Ok(value) => Ok(Ok(value)),
            Err(UsageMeterRecordUsageInvocationError::Domain(error)) => Ok(Err(error)),
            Err(UsageMeterRecordUsageInvocationError::Runtime(error)) => Err(error),
        }
    }
}

pub trait UsageMeterProvider: fmt::Debug + 'static {
    fn correct_usage(&self, context: InvocationContext, request: CorrectUsageRequest) -> NativeRequestFuture<UsageMeterCorrectUsage>;
    fn read_usage_window(&self, context: InvocationContext, request: ReadUsageWindowRequest) -> NativeRequestFuture<UsageMeterReadUsageWindow>;
    fn record_usage(&self, context: InvocationContext, request: RecordUsageRequest) -> NativeRequestFuture<UsageMeterRecordUsage>;
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_lower_usage_meter {
    ($plugin:ty, $support:path) => {
        use $support as __LensoNativeSupportUsageMeter;
        impl $crate::UsageMeterProvider for $plugin {
        fn correct_usage(&self, context: __LensoNativeSupportUsageMeter::InvocationContext, request: $crate::CorrectUsageRequest) -> __LensoNativeSupportUsageMeter::NativeRequestFuture<$crate::UsageMeterCorrectUsage> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::correct_usage(&plugin, context, request).await;
                $crate::__LensoIntoUsageMeterCorrectUsageResult::__lenso_into_result(result)
            })
        }
        fn read_usage_window(&self, context: __LensoNativeSupportUsageMeter::InvocationContext, request: $crate::ReadUsageWindowRequest) -> __LensoNativeSupportUsageMeter::NativeRequestFuture<$crate::UsageMeterReadUsageWindow> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::read_usage_window(&plugin, context, request).await;
                $crate::__LensoIntoUsageMeterReadUsageWindowResult::__lenso_into_result(result)
            })
        }
        fn record_usage(&self, context: __LensoNativeSupportUsageMeter::InvocationContext, request: $crate::RecordUsageRequest) -> __LensoNativeSupportUsageMeter::NativeRequestFuture<$crate::UsageMeterRecordUsage> {
            let plugin = self.clone();
            ::std::boxed::Box::pin(async move {
                let result = <$plugin>::record_usage(&plugin, context, request).await;
                $crate::__LensoIntoUsageMeterRecordUsageResult::__lenso_into_result(result)
            })
        }
        }
    };
}

#[derive(Debug)]
struct UsageMeterRequestEndpoint { provider: Rc<dyn UsageMeterProvider> }

#[derive(Debug)]
pub struct UsageMeterEndpoint<P: UsageMeterProvider> { provider: Rc<P>, request_endpoint: UsageMeterRequestEndpoint }
impl<P: UsageMeterProvider> UsageMeterEndpoint<P> {
    pub fn new(provider: P) -> Self {
        let provider = Rc::new(provider);
        let request_provider: Rc<dyn UsageMeterProvider> = provider.clone();
        Self { provider, request_endpoint: UsageMeterRequestEndpoint { provider: request_provider } }
    }
}

impl<P: UsageMeterProvider> NativeRequestEndpoint for UsageMeterEndpoint<P> {
    fn capability_id(&self) -> &'static str { CAPABILITY_ID }
    fn descriptor_version(&self) -> &'static str { DESCRIPTOR_VERSION }
    fn operations(&self) -> &'static [&'static str] { &[
        CORRECT_USAGE_OPERATION,
        READ_USAGE_WINDOW_OPERATION,
        RECORD_USAGE_OPERATION,
    ] }
    fn typed_endpoint(&self) -> Option<&dyn std::any::Any> { Some(&self.request_endpoint) }
    fn invoke(&self, operation: &str, request: Box<dyn std::any::Any>, context: InvocationContext) -> LocalBoxFuture<'static, Result<Result<Box<dyn std::any::Any>, Box<dyn std::any::Any>>, RuntimeFailure>> {
        match operation {
            CORRECT_USAGE_OPERATION => {
                let Ok(request) = request.downcast::<CorrectUsageRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).correct_usage(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            READ_USAGE_WINDOW_OPERATION => {
                let Ok(request) = request.downcast::<ReadUsageWindowRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).read_usage_window(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            },
            RECORD_USAGE_OPERATION => {
                let Ok(request) = request.downcast::<RecordUsageRequest>() else {
                    return Box::pin(futures::future::ready(Err(RuntimeFailure::ProtocolViolation { capability: CAPABILITY_ID })));
                };
                let invocation = Rc::clone(&self.provider).record_usage(context, *request);
                Box::pin(async move {
                    invocation.await.map(|result| {
                        result
                            .map(|value| Box::new(value) as Box<dyn std::any::Any>)
                            .map_err(|error| Box::new(error) as Box<dyn std::any::Any>)
                    })
                })
            }
            _ => Box::pin(futures::future::ready(Err(RuntimeFailure::UnknownOperation { capability: CAPABILITY_ID, operation: operation.to_owned() }))),
        }
    }
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_endpoints_usage_meter {
    ($provider:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let endpoint = ::std::rc::Rc::new($crate::UsageMeterEndpoint::new($provider));
        (
            vec![endpoint.clone() as ::std::rc::Rc<dyn __LensoNativeSupport::NativeRequestEndpoint>],
            vec![],
            vec![],
        )
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __lenso_native_provide_usage_meter {
    ($provider:expr, $lifecycle:expr, $support:path) => {{
        use $support as __LensoNativeSupport;
        let (request_endpoints, stream_endpoints, event_endpoints) =
            $crate::__lenso_native_endpoints_usage_meter!($provider, $support);
        __LensoNativeSupport::NativePluginInstance::with_all_endpoints(
            request_endpoints,
            stream_endpoints,
            event_endpoints,
            $lifecycle,
        )
    }};
}

#[derive(Debug)]
pub struct UsageMeterClient {
    correct_usage: NativeRequestHandle<UsageMeterCorrectUsage>,
    read_usage_window: NativeRequestHandle<UsageMeterReadUsageWindow>,
    record_usage: NativeRequestHandle<UsageMeterRecordUsage>,
}
impl UsageMeterClient {
    pub fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        <Self as CapabilityClient>::from_dependencies(dependencies)
    }

    pub async fn correct_usage(&self, request: CorrectUsageRequest) -> Result<CorrectUsageResponse, UsageMeterCorrectUsageInvocationError> {
        self.correct_usage.invoke(CORRECT_USAGE_OPERATION, request).await
            .map_err(UsageMeterCorrectUsageInvocationError::Runtime)?
            .map_err(UsageMeterCorrectUsageInvocationError::Domain)
    }

    pub async fn correct_usage_with_context(&self, context: InvocationContext, request: CorrectUsageRequest) -> Result<CorrectUsageResponse, UsageMeterCorrectUsageInvocationError> {
        self.correct_usage.invoke_with_context(CORRECT_USAGE_OPERATION, context, request).await
            .map_err(UsageMeterCorrectUsageInvocationError::Runtime)?
            .map_err(UsageMeterCorrectUsageInvocationError::Domain)
    }

    pub async fn read_usage_window(&self, request: ReadUsageWindowRequest) -> Result<ReadUsageWindowResponse, UsageMeterReadUsageWindowInvocationError> {
        self.read_usage_window.invoke(READ_USAGE_WINDOW_OPERATION, request).await
            .map_err(UsageMeterReadUsageWindowInvocationError::Runtime)?
            .map_err(UsageMeterReadUsageWindowInvocationError::Domain)
    }

    pub async fn read_usage_window_with_context(&self, context: InvocationContext, request: ReadUsageWindowRequest) -> Result<ReadUsageWindowResponse, UsageMeterReadUsageWindowInvocationError> {
        self.read_usage_window.invoke_with_context(READ_USAGE_WINDOW_OPERATION, context, request).await
            .map_err(UsageMeterReadUsageWindowInvocationError::Runtime)?
            .map_err(UsageMeterReadUsageWindowInvocationError::Domain)
    }

    pub async fn record_usage(&self, request: RecordUsageRequest) -> Result<RecordUsageResponse, UsageMeterRecordUsageInvocationError> {
        self.record_usage.invoke(RECORD_USAGE_OPERATION, request).await
            .map_err(UsageMeterRecordUsageInvocationError::Runtime)?
            .map_err(UsageMeterRecordUsageInvocationError::Domain)
    }

    pub async fn record_usage_with_context(&self, context: InvocationContext, request: RecordUsageRequest) -> Result<RecordUsageResponse, UsageMeterRecordUsageInvocationError> {
        self.record_usage.invoke_with_context(RECORD_USAGE_OPERATION, context, request).await
            .map_err(UsageMeterRecordUsageInvocationError::Runtime)?
            .map_err(UsageMeterRecordUsageInvocationError::Domain)
    }
}

impl CapabilityClient for UsageMeterClient {
    type Dependencies = PluginDependencies;
    type Error = RuntimeFailure;

    const CAPABILITY_ID: &'static str = CAPABILITY_ID;
    const DESCRIPTOR_VERSION: &'static str = DESCRIPTOR_VERSION;

    fn from_dependencies(dependencies: &PluginDependencies) -> Result<Self, RuntimeFailure> {
        Ok(Self {
            correct_usage: dependencies.one::<UsageMeterCorrectUsage>()?,
            read_usage_window: dependencies.one::<UsageMeterReadUsageWindow>()?,
            record_usage: dependencies.one::<UsageMeterRecordUsage>()?,
        })
    }

    fn already_connected() -> RuntimeFailure {
        RuntimeFailure::PluginFailure {
            detail: format!("Capability Port {CAPABILITY_ID} was connected more than once"),
        }
    }
}

impl CapabilityClientMany for UsageMeterClient {
    fn many_from_dependencies(
        dependencies: &PluginDependencies,
    ) -> Result<Vec<BoundCapabilityClient<Self>>, RuntimeFailure> {
        dependencies
            .bindings()
            .iter()
            .filter(|binding| binding.capability_id() == CAPABILITY_ID)
            .map(|binding| {
                Ok(BoundCapabilityClient::new(
                    binding.provider_instance(),
                    Self {
                    correct_usage: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<UsageMeterCorrectUsage>()?,
                    read_usage_window: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<UsageMeterReadUsageWindow>()?,
                    record_usage: binding.handle().ok_or(RuntimeFailure::Unavailable { capability: CAPABILITY_ID })?.typed::<UsageMeterRecordUsage>()?,
                    },
                ))
            })
            .collect()
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum UsageMeterCorrectUsageInvocationError {
    Domain(CorrectUsageError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum UsageMeterReadUsageWindowInvocationError {
    Domain(ReadUsageWindowError),
    Runtime(RuntimeFailure),
}
#[derive(Clone, Debug, PartialEq)]
pub enum UsageMeterRecordUsageInvocationError {
    Domain(RecordUsageError),
    Runtime(RuntimeFailure),
}
